version: '3'

services:
  dev:
    depends_on:
      - db_dev
    image: ${DOCKER_HTTP_IMAGE}
    ports:
      - '${APP_DEV_HTTP_PORT}:80'
      - '${APP_DEV_HTTPS_PORT}:443'
    volumes:
      - ${PATH_MOUNT_HTTP}:/home/${COMPOSE_PROJECT_NAME}
    working_dir: /home/${COMPOSE_PROJECT_NAME}
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    networks:
      dev:
        aliases:
          - ${APP_DEV_HOST}

  test:
    depends_on:
      - db_test
    image: ${DOCKER_HTTP_IMAGE}
    ports:
      - '${APP_TEST_HTTP_PORT}:80'
      - '${APP_TEST_HTTPS_PORT}:443'
    volumes:
      - ${PATH_MOUNT_HTTP}:/home/${COMPOSE_PROJECT_NAME}
    working_dir: /home/${COMPOSE_PROJECT_NAME}
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    networks:
      dev:
        aliases:
          - ${APP_TEST_HOST}

  db_dev:
    image: ${DOCKER_DB_IMAGE}
    working_dir: /image
    volumes:
      - ${PATH_MOUNT_DB}/dev:/var/lib/db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '${APP_DEV_DB_PORT}:3306'
    networks:
      dev:
        aliases:
          - ${APP_DEV_DB_HOST}

  db_test:
    image: ${DOCKER_DB_IMAGE}
    working_dir: /image
    volumes:
      - ${PATH_MOUNT_DB}/test:/var/lib/db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '${APP_TEST_DB_PORT}:3306'
    networks:
      dev:
        aliases:
          - ${APP_TEST_DB_HOST}

networks:
  prod:
  dev:
